import React from "react";
import {
    FolderOpenOutlined,
    EyeOutlined,
    EditOutlined,
    StopOutlined,
    TeamOutlined,
    AimOutlined,
    FileTextOutlined,
} from "@ant-design/icons";
import { ALL_PERMISSIONS } from "@/config/permissions";
import type { LotusGuide } from "./guideRegistry";

export const DOSSIER_GUIDES: LotusGuide[] = [
    {
        id: "hr-dossier-overview",
        title: "Tổng quan bộ hồ sơ phòng/ban",
        description: "Nắm rõ bộ hồ sơ cần có, dữ liệu cần chuẩn bị và thứ tự hoàn thiện.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "Khu vực training",
        routePrefix: "/admin/departments",
        exactRoute: false,
        routePattern: /^\/admin\/departments/,
        icon: <FolderOpenOutlined />,
        steps: [
            {
                id: "hr-dossier-overview-1",
                targetId: "department-search-input",
                title: "Bộ hồ sơ nhân sự cần hoàn thiện",
                description: "Mỗi phòng ban cần có đủ 9 nhóm dữ liệu: cơ cấu tổ chức, mục tiêu nhiệm vụ, mô tả công việc, phân quyền, quy trình quy định, lộ trình thăng tiến, khung lương, tiêu chí đánh giá và bản đồ chức danh. Ngoài ra cần cấu hình chức danh nền để các mục JD, lộ trình, lương và đánh giá liên kết đúng.",
                placement: "bottom",
            },
            {
                id: "hr-dossier-overview-2",
                targetId: "department-more-button",
                title: "Cách mở từng mục",
                description: "Nhấn vào nút 3 chấm của phòng ban cần thiết lập. Menu sẽ hiển thị các mục hồ sơ liên quan như Sơ đồ tổ chức, Mục tiêu - Nhiệm vụ, Quy trình phòng ban, Phân quyền, Lộ trình thăng tiến, Khung lương, Bản đồ chức danh và Cấu hình chức danh.",
                placement: "left",
            },
            {
                id: "hr-dossier-overview-3",
                targetId: "department-more-button",
                title: "Nguyên tắc làm đúng thứ tự",
                description: "Hãy làm từ dữ liệu nền trước: Sơ đồ tổ chức và chức danh. Sau đó mới nhập mục tiêu, JD, phân quyền, quy trình, lộ trình, khung lương và tiêu chí đánh giá. Cách này giúp các mục sau có đủ dữ liệu để đối chiếu và tránh nhập trùng.",
                placement: "left",
            },
            {
                id: "hr-dossier-overview-4",
                targetId: "department-search-input",
                title: "Kiểm tra trước khi hoàn tất",
                description: "Sau khi nhập xong, quay lại danh sách phòng ban để kiểm tra từng phòng ban đã có đủ dữ liệu chính chưa: có sơ đồ, có mục tiêu, có JD cho chức danh trọng yếu, có quy trình ban hành, có phân quyền và có khung lương tương ứng.",
                placement: "bottom",
            },
        ],
    },
    {
        id: "hr-dossier-implementation-plan",
        title: "Kế hoạch triển khai bộ hồ sơ",
        description: "Plan từng giai đoạn để hoàn thiện hồ sơ phòng/ban theo cách dễ kiểm soát.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "Khu vực training",
        routePrefix: "/admin/departments",
        exactRoute: false,
        routePattern: /^\/admin\/departments/,
        icon: <AimOutlined />,
        steps: [
            {
                id: "hr-dossier-plan-1",
                targetId: "department-search-input",
                title: "Giai đoạn 1: Chọn phạm vi làm trước",
                description: "Chọn một phòng ban ưu tiên để làm mẫu. Tìm phòng ban trên danh sách, thống nhất người phụ trách nhập liệu, người kiểm tra và thời hạn hoàn thành. Không nên nhập tất cả phòng ban cùng lúc khi chưa có mẫu chuẩn.",
                placement: "bottom",
            },
            {
                id: "hr-dossier-plan-2",
                targetId: "department-more-button",
                title: "Giai đoạn 2: Chuẩn hóa cấu trúc nền",
                description: "Mở Sơ đồ tổ chức, Cấu hình chức danh và Bản đồ chức danh để kiểm tra cây phòng ban, chức danh được gán, cấp bậc và số lượng nhân sự. Đây là nền để các mục JD, khung lương, lộ trình thăng tiến và phân quyền dùng chung.",
                placement: "left",
            },
            {
                id: "hr-dossier-plan-3",
                targetId: "department-more-button",
                title: "Giai đoạn 3: Nhập nội dung vận hành",
                description: "Tiếp tục hoàn thiện Mục tiêu - Nhiệm vụ, Mô tả công việc và Quy trình phòng ban. Với mỗi chức danh quan trọng, cần có mục tiêu hoặc nhiệm vụ liên quan, JD rõ trách nhiệm và quy trình làm việc đi kèm.",
                placement: "left",
            },
            {
                id: "hr-dossier-plan-4",
                targetId: "department-more-button",
                title: "Giai đoạn 4: Thiết lập quản trị",
                description: "Thiết lập Phân quyền, Lộ trình thăng tiến, Khung lương và Tiêu chí đánh giá. Mục tiêu là xác định ai được thao tác dữ liệu, nhân sự phát triển theo nấc nào, mỗi nấc có mức lương nào và đánh giá bằng tiêu chí gì.",
                placement: "left",
            },
            {
                id: "hr-dossier-plan-5",
                targetId: "department-search-input",
                title: "Giai đoạn 5: Rà soát và nhân rộng",
                description: "Sau khi phòng ban mẫu hoàn tất, kiểm tra chéo các điểm thiếu: chức danh chưa có JD, bậc lương chưa có tiêu chí, quy trình chưa ban hành, quyền chưa đúng vai trò. Khi mẫu ổn định, dùng cùng thứ tự này để triển khai cho các phòng ban còn lại.",
                placement: "bottom",
            },
        ],
    },
    {
        id: "hr-dossier-view-department",
        title: "Xem hồ sơ phòng ban",
        description: "Kiểm tra thông tin phòng ban trước khi cấu hình hoặc rà soát bộ hồ sơ.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "Quản trị hồ sơ",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        icon: <EyeOutlined />,
        steps: [
            {
                id: "hr-dossier-view-1",
                targetId: "department-search-input",
                title: "Bước 1: Tìm đúng phòng ban",
                description: "Nhập mã, tên phòng ban hoặc công ty để lọc đúng phòng ban cần xem. Nên kiểm tra đúng đơn vị trước khi vào cấu hình bộ hồ sơ.",
                placement: "bottom",
            },
            {
                id: "hr-dossier-view-2",
                targetId: "department-detail-button",
                title: "Bước 2: Mở chi tiết phòng ban",
                description: "Nhấn biểu tượng mắt để xem thông tin phòng ban, công ty trực thuộc và các dữ liệu mô tả cơ bản trước khi thao tác tiếp.",
                placement: "left",
            },
        ],
    },
    {
        id: "hr-dossier-edit-department",
        title: "Sửa thông tin phòng ban",
        description: "Cập nhật mã, tên, tên tiếng Anh hoặc công ty liên kết của phòng ban.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "Quản trị hồ sơ",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        icon: <EditOutlined />,
        steps: [
            {
                id: "hr-dossier-edit-1",
                targetId: "department-search-input",
                title: "Bước 1: Tìm phòng ban cần sửa",
                description: "Dùng tìm kiếm để xác định đúng phòng ban. Nếu phòng ban đã có dữ liệu liên kết như chức danh, JD, lương hoặc quy trình, hãy kiểm tra kỹ trước khi đổi thông tin.",
                placement: "bottom",
            },
            {
                id: "hr-dossier-edit-2",
                targetId: "department-edit-button",
                title: "Bước 2: Mở form cập nhật",
                description: "Nhấn biểu tượng bút để mở form cập nhật phòng ban.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-edit-3",
                targetId: ".department-form-modal .ant-modal-content",
                title: "Bước 3: Cập nhật và lưu",
                description: "Điều chỉnh các thông tin cần sửa, đặc biệt là tên phòng ban và công ty liên kết. Sau khi lưu, các màn hình bộ hồ sơ sẽ sử dụng thông tin mới này.",
                placement: "right",
            },
        ],
    },
    {
        id: "hr-dossier-delete-department",
        title: "Xóa phòng ban đúng điều kiện",
        description: "Hướng dẫn xóa phòng ban và các điểm cần kiểm tra để tránh mất dữ liệu liên kết.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "Quản trị hồ sơ",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        icon: <StopOutlined />,
        steps: [
            {
                id: "hr-dossier-delete-1",
                targetId: "department-search-input",
                title: "Bước 1: Kiểm tra phòng ban cần xóa",
                description: "Tìm đúng phòng ban và rà soát xem phòng ban còn nhân sự, chức danh, quy trình, JD, lộ trình hoặc khung lương đang sử dụng hay không.",
                placement: "bottom",
            },
            {
                id: "hr-dossier-delete-2",
                targetId: "department-more-button",
                title: "Bước 2: Mở menu thao tác",
                description: "Nhấn nút ba chấm của phòng ban. Thao tác xóa nằm trong nhóm thao tác cuối menu và chỉ hiện khi tài khoản có quyền.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-delete-3",
                targetId: ".guide-department-delete",
                title: "Bước 3: Chọn Xóa phòng ban",
                description: "Chỉ xác nhận xóa khi phòng ban không còn được dùng trong vận hành. Nếu vẫn còn dữ liệu liên kết, nên chuyển dữ liệu hoặc ngưng sử dụng theo quy trình nội bộ trước.",
                placement: "left",
            },
        ],
    },
    {
        id: "hr-dossier-job-title-config",
        title: "Cấu hình chức danh cho phòng ban",
        description: "Gán chức danh vào phòng ban để làm nền cho JD, lương, lộ trình và tiêu chí đánh giá.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "Cấu hình nền",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        allowedRoutes: [/^\/admin\/departments$/],
        icon: <TeamOutlined />,
        steps: [
            {
                id: "hr-dossier-job-title-config-1",
                targetId: "department-more-button",
                title: "Bước 1: Mở menu phòng ban",
                description: "Nhấn nút ba chấm của phòng ban cần gán chức danh.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-job-title-config-2",
                targetId: ".guide-department-job-title",
                title: "Bước 2: Chọn Cấu hình chức danh",
                description: "Mở màn hình danh sách chức danh đang thuộc phòng ban. Đây là phần rất quan trọng vì chức danh là dữ liệu nền cho JD, khung lương, lộ trình và tiêu chí đánh giá.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-job-title-config-3",
                targetId: "department-job-title-table",
                title: "Bước 3: Kiểm tra chức danh đã gán",
                description: "Bảng này cho biết phòng ban hiện có những chức danh nào. Hãy kiểm tra chức danh chính, cấp bậc, trạng thái và các cấu hình liên quan trước khi gán thêm.",
                placement: "top",
            },
            {
                id: "hr-dossier-job-title-config-4",
                targetId: "department-job-title-assign-button",
                title: "Bước 4: Gán thêm chức danh",
                description: "Nhấn nút này để mở drawer gán chức danh. Nếu màn hình đang rỗng, bạn cũng có thể dùng nút 'Gán chức danh ngay' trong vùng trống.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-job-title-config-5",
                targetId: "department-job-title-assign-table",
                title: "Bước 5: Chọn chức danh phù hợp",
                description: "Lọc theo tên, trạng thái hoặc band, sau đó chọn các chức danh cần đưa vào phòng ban. Tránh gán chức danh không thuộc phạm vi vận hành của phòng ban.",
                placement: "top",
            },
            {
                id: "hr-dossier-job-title-config-6",
                targetId: "department-job-title-assign-save-button",
                title: "Bước 6: Xác nhận gán",
                description: "Sau khi chọn xong, nhấn Gán để lưu. Khi quay lại bảng chức danh, dùng danh sách này để tiếp tục cấu hình JD, lộ trình, khung lương và tiêu chí đánh giá.",
                placement: "left",
            },
        ],
    },
    {
        id: "hr-dossier-completeness-check",
        title: "Rà soát độ hoàn thiện hồ sơ",
        description: "Kiểm tra các điểm thiếu giữa chức danh, JD, quy trình, lương, lộ trình và phân quyền.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "Khu vực training",
        routePrefix: "/admin/departments",
        exactRoute: false,
        routePattern: /^\/admin\/departments/,
        icon: <FolderOpenOutlined />,
        steps: [
            {
                id: "hr-dossier-completeness-1",
                targetId: "department-search-input",
                title: "Bước 1: Chọn phòng ban cần rà soát",
                description: "Tìm phòng ban đã cấu hình gần xong để kiểm tra thiếu sót. Nên rà soát từng phòng ban, không kiểm tra dàn trải nhiều phòng ban cùng lúc.",
                placement: "bottom",
            },
            {
                id: "hr-dossier-completeness-2",
                targetId: "department-more-button",
                title: "Bước 2: Mở các mục cần đối chiếu",
                description: "Dùng menu ba chấm để lần lượt mở Cấu hình chức danh, Bản đồ chức danh, Mô tả công việc, Khung lương, Lộ trình thăng tiến, Quy trình và Phân quyền.",
                placement: "left",
            },
            {
                id: "hr-dossier-completeness-3",
                targetId: "department-more-button",
                title: "Bước 3: Đối chiếu theo chức danh",
                description: "Với mỗi chức danh đang hoạt động, kiểm tra đủ 5 điểm: có JD, có bậc hoặc lộ trình, có khung lương, có tiêu chí đánh giá và có quy trình liên quan. Chức danh thiếu một trong các điểm này cần được bổ sung trước khi nghiệm thu hồ sơ.",
                placement: "left",
            },
            {
                id: "hr-dossier-completeness-4",
                targetId: "department-more-button",
                title: "Bước 4: Kiểm tra quyền vận hành",
                description: "Sau khi dữ liệu đã đủ, mở Phân quyền để kiểm tra ai được xem, cập nhật, duyệt hoặc xóa. Đây là bước giúp bộ hồ sơ vận hành được sau khi bàn giao.",
                placement: "left",
            },
        ],
    },
    {
        id: "hr-dossier-advanced-features",
        title: "Các tính năng nổi bật của bộ hồ sơ",
        description: "Giúp người dùng hiểu bộ hồ sơ không chỉ lưu dữ liệu mà còn liên kết quản trị nhân sự.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "Khu vực training",
        routePrefix: "/admin/departments",
        exactRoute: false,
        routePattern: /^\/admin\/departments/,
        icon: <AimOutlined />,
        steps: [
            {
                id: "hr-dossier-advanced-1",
                targetId: "department-more-button",
                title: "Liên kết dữ liệu theo phòng ban",
                description: "Từ một phòng ban, menu ba chấm cho phép đi tới nhiều phần liên quan. Người dùng có thể cấu hình cơ cấu, chức danh, quy trình, phân quyền, lương và lộ trình mà vẫn giữ dữ liệu theo cùng một đơn vị.",
                placement: "left",
            },
            {
                id: "hr-dossier-advanced-2",
                targetId: "department-more-button",
                title: "Bản đồ chức danh để nhìn tổng thể",
                description: "Bản đồ chức danh giúp nhìn nhanh phòng ban có bao nhiêu chức danh, vị trí nào đang có nhân sự, vị trí nào cần bổ sung JD, lương hoặc lộ trình.",
                placement: "left",
            },
            {
                id: "hr-dossier-advanced-3",
                targetId: "department-more-button",
                title: "Phân quyền theo vai trò vận hành",
                description: "Phân quyền giúp tách rõ người được xem, người được cập nhật, người được duyệt và người được quản trị. Đây là phần cần cấu hình trước khi bàn giao cho các phòng ban tự vận hành.",
                placement: "left",
            },
            {
                id: "hr-dossier-advanced-4",
                targetId: "department-more-button",
                title: "Liên kết lộ trình - lương - đánh giá",
                description: "Khi chức danh đã được gán đúng, hệ thống có thể dùng chung dữ liệu này cho lộ trình thăng tiến, khung lương và tiêu chí đánh giá. Nhờ vậy bộ hồ sơ không bị rời rạc giữa các màn hình.",
                placement: "left",
            },
        ],
    },
    {
        id: "hr-dossier-org-chart",
        title: "1. Sơ đồ tổ chức vận hành nội bộ",
        description: "Dựng cấu trúc phòng ban, bộ phận, vị trí và quan hệ báo cáo trước khi làm các mục còn lại.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "1. Sơ đồ & Cấu trúc",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        allowedRoutes: [/^\/admin\/departments\/[^/]+\/org-chart/],
        icon: <AimOutlined />,
        steps: [
            {
                id: "hr-dossier-org-chart-1",
                targetId: "department-more-button",
                title: "Bước 1: Mở menu tùy chọn phòng ban",
                description: "Tìm phòng ban cần thiết lập sơ đồ, sau đó nhấn VÀO NÚT BA CHẤM ở hàng phòng ban đó để xem các tùy chọn.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-org-chart-2",
                targetId: ".guide-department-org-chart",
                title: "Bước 2: Chọn Sơ đồ tổ chức",
                description: "Nhấn vào mục 'Sơ đồ tổ chức' để vào trang quản lý sơ đồ vận hành nội bộ của phòng ban.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-org-chart-3-search",
                targetId: "org-chart-search-input",
                title: "Bước 3: Tìm kiếm nhanh vị trí/nhân sự",
                description: "Sử dụng thanh tìm kiếm ở góc trên bên trái để tra cứu nhanh bất kỳ vị trí công việc hoặc tên nhân sự nào trên sơ đồ. Hệ thống sẽ tự động tìm và zoom thẳng tới vị trí đó.",
                placement: "bottom",
            },
            {
                id: "hr-dossier-org-chart-5-canvas",
                targetId: "dept-org-chart-canvas",
                title: "Bước 4: Xem sơ đồ & Kéo thả sắp xếp",
                description: "Đây là vùng sơ đồ chính. Bạn có thể kéo thả để di chuyển các ô vị trí, cuộn chuột để phóng to/thu nhỏ (Zoom) hoặc xem bản đồ thu nhỏ (MiniMap) góc dưới. Sau khi sắp xếp xong, hãy nhớ bấm 'Lưu vị trí' ở góc trên bên phải để cố định sơ đồ nhé!",
                placement: "top",
            },
            {
                id: "hr-dossier-org-chart-3-settings",
                targetId: "org-chart-settings-button",
                title: "Bước 5: Menu Tùy chỉnh nâng cao",
                description: "Nhấn nút Tùy chỉnh ở góc trên bên phải để mở rộng các tính năng quản lý sơ đồ.",
                placement: "bottom",
                actionType: "click",
            },
            {
                id: "hr-dossier-org-chart-3-settings-expanded",
                targetId: "org-chart-settings-dropdown",
                title: "Bước 6: Các tính năng Tùy chỉnh",
                description: "Menu bung ra gồm 4 tính năng: (1) Hoàn tác: trở lại vị trí cũ trước khi kéo thả. (2) Tự căn chỉnh: sắp xếp cây tự động cân đối. (3) Khóa/Mở khóa di chuyển: cố định vị trí các node. (4) Chế độ xem: chuyển đổi giữa Chi tiết và Tổng quan tối giản.",
                placement: "left",
            },
            {
                id: "hr-dossier-org-chart-4",
                targetId: "org-chart-add-button",
                title: "Bước 7: Mở popup Thêm vị trí mới",
                description: "Nhấn nút '+ Thêm vị trí' ở góc trên bên phải để bắt đầu khai báo phòng ban con hoặc chức danh công việc.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-org-chart-modal-single",
                targetId: ".org-node-form-modal .ant-modal-content",
                title: "Bước 8: Khai báo vị trí trong modal",
                description: "Trong modal này, bạn có thể tạo một vị trí bằng tab 'Một vị trí' hoặc tạo nhiều vị trí cùng lúc bằng tab 'Hàng loạt'. Chọn đúng loại mục như Phòng ban hoặc Chức danh, rồi nhập tên, mã cấp bậc, người đảm nhiệm, đơn vị cấp trên và JD liên quan để sơ đồ liên kết đúng phân cấp.",
                placement: "right",
                inModal: true,
            },
        ],
    },
    {
        id: "hr-dossier-objectives",
        title: "2. Bảng mục tiêu và nhiệm vụ",
        description: "Nhập mục tiêu phòng ban, nhiệm vụ chính, người phụ trách, thời hạn và căn cứ theo dõi.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "2. Mục tiêu & Nhiệm vụ",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        allowedRoutes: [/^\/admin\/departments\/\d+\/objectives-tasks/],
        requiredPermission: ALL_PERMISSIONS.DEPARTMENT_OBJECTIVES.VIEW,
        icon: <AimOutlined />,
        steps: [
            {
                id: "hr-dossier-objectives-1",
                targetId: "department-more-button",
                title: "Bước 1: Mở menu tùy chọn phòng ban",
                description: "Nhấn VÀO NÚT BA CHẤM ở hàng phòng ban bạn muốn thiết lập mục tiêu.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-objectives-2",
                targetId: ".guide-department-objectives",
                title: "Bước 2: Chọn Mục tiêu - Nhiệm vụ",
                description: "Nhấn vào 'Mục tiêu - Nhiệm vụ' để truy cập trang OKRs của phòng ban.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-objectives-3",
                targetId: "department-objectives-edit-btn",
                title: "Bước 3: Bật chế độ chỉnh sửa",
                description: "Nhấn nút 'Chỉnh sửa' để bắt đầu thêm hoặc cập nhật mục tiêu và nhiệm vụ của phòng ban.",
                placement: "bottom",
                actionType: "click",
            },
            {
                id: "hr-dossier-objectives-4",
                targetId: "department-objectives-add-obj-btn",
                title: "Bước 4: Thêm mục tiêu",
                description: "Nhấn nút này để thêm một dòng mục tiêu mới. Nên nhập mục tiêu theo cấu trúc rõ ràng: kết quả cần đạt, chỉ số đo lường, người phụ trách, thời hạn và ghi chú nếu có phụ thuộc vào phòng ban khác.",
                placement: "top",
                actionType: "click",
            },
            {
                id: "hr-dossier-objectives-5",
                targetId: "department-objectives-save-btn",
                title: "Bước 5: Lưu thay đổi",
                description: "Sau khi điền xong, nhấn 'Lưu thay đổi' để hệ thống ghi nhận. Trước khi lưu, kiểm tra mục tiêu có gắn đúng phòng ban, nhiệm vụ có người phụ trách và không còn dòng trống hoặc nội dung trùng lặp.",
                placement: "bottom",
            },
        ],
    },
    {
        id: "hr-dossier-job-description",
        title: "3. Bảng mô tả công việc chi tiết",
        description: "Tạo JD cho từng chức danh, nhập mục tiêu vị trí, nhiệm vụ, yêu cầu, quyền hạn và luồng phê duyệt.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "3. Mô tả công việc",
        routePrefix: "/admin/job-descriptions",
        exactRoute: true,
        icon: <FileTextOutlined />,
        steps: [
            {
                id: "hr-dossier-jd-1",
                targetId: "job-description-search-input",
                title: "Bước 1: Kiểm tra JD đã có chưa",
                description: "Tìm theo tên vị trí hoặc chức danh để kiểm tra xem mô tả công việc đã tồn tại chưa. Nếu đã có JD, hãy mở bản hiện tại để cập nhật thay vì tạo mới, tránh nhiều phiên bản cho cùng một chức danh.",
                placement: "bottom",
            },
            {
                id: "hr-dossier-jd-2",
                targetId: "job-description-add-button",
                title: "Bước 2: Tạo JD mới",
                description: "Nhấn VÀO NÚT NÀY để mở form tạo bản mô tả công việc mới cho chức danh của phòng ban.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-jd-3",
                targetId: ".job-description-form-modal .ant-modal-content",
                title: "Bước 3: Điền thông tin JD",
                description: "Nhập đầy đủ: tên vị trí, phòng ban, chức danh, mục tiêu công việc, nhiệm vụ chính, quyền hạn, trách nhiệm, yêu cầu kiến thức - kỹ năng - kinh nghiệm và chế độ đãi ngộ. Sau khi lưu, gửi duyệt hoặc ban hành khi nội dung đã được kiểm tra.",
                placement: "right",
            },
        ],
    },
    {
        id: "hr-dossier-permissions",
        title: "4. Bảng phân quyền",
        description: "Xác định vai trò nào được xem, thêm, sửa, xóa, duyệt hoặc quản lý từng nhóm dữ liệu.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "4. Phân quyền",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        allowedRoutes: [/^\/admin\/departments\/[^/]+\/permissions/],
        icon: <FolderOpenOutlined />,
        steps: [
            {
                id: "hr-dossier-permissions-1",
                targetId: "department-more-button",
                title: "Bước 1: Mở menu tùy chọn phòng ban",
                description: "Nhấn VÀO NÚT BA CHẤM ở hàng phòng ban bạn muốn thiết lập phân quyền.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-permissions-2",
                targetId: ".guide-department-permissions",
                title: "Bước 2: Chọn Phân quyền",
                description: "Nhấn vào 'Phân quyền' để mở bảng ma trận phân quyền của phòng ban.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-permissions-3",
                targetId: "dept-permissions-content",
                title: "Bước 3: Thiết lập ma trận quyền",
                description: "Bảng này hiển thị chức năng theo hàng và vai trò theo cột. Tích quyền theo đúng trách nhiệm: nhân sự vận hành thường cần xem và cập nhật, trưởng bộ phận cần duyệt hoặc xác nhận, quản trị hệ thống mới nên có quyền xóa hoặc cấu hình.",
                placement: "top",
            },
        ],
    },
    {
        id: "hr-dossier-procedures",
        title: "5. Danh mục quy trình, quy định",
        description: "Tập hợp quy trình, quy định, biểu mẫu và tài liệu hướng dẫn đang áp dụng cho phòng ban.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "5. Quy trình & Quy định",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        allowedRoutes: [/^\/admin\/departments\/[^/]+\/procedures/],
        icon: <FileTextOutlined />,
        steps: [
            {
                id: "hr-dossier-procedures-1",
                targetId: "department-more-button",
                title: "Bước 1: Mở menu tùy chọn phòng ban",
                description: "Nhấn VÀO NÚT BA CHẤM ở hàng phòng ban bạn muốn quản lý quy trình.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-procedures-2",
                targetId: ".guide-department-procedures",
                title: "Bước 2: Chọn Quy trình phòng ban",
                description: "Nhấn vào 'Quy trình phòng ban' để truy cập danh mục quy trình, quy định của phòng ban.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-procedures-3",
                targetId: "department-procedure-add-button",
                title: "Bước 3: Thêm quy trình mới",
                description: "Nhấn VÀO NÚT NÀY để tạo quy trình mới. Điền tên quy trình, mã hoặc nhóm quy trình, mô tả phạm vi áp dụng, người phụ trách, phiên bản, trạng thái và tải file đính kèm nếu có. Chỉ đặt 'Ban hành' khi tài liệu đã được duyệt.",
                placement: "left",
                actionType: "click",
            },
        ],
    },
    {
        id: "hr-dossier-career-paths",
        title: "6. Lộ trình thăng tiến",
        description: "Tạo các nấc phát triển nghề nghiệp theo chức danh, năng lực, KPI và điều kiện lên bậc.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "6. Lộ trình thăng tiến",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        allowedRoutes: [/^\/admin\/departments\/[^/]+\/career-paths/],
        icon: <AimOutlined />,
        steps: [
            {
                id: "hr-dossier-career-paths-1",
                targetId: "department-more-button",
                title: "Bước 1: Mở menu tùy chọn phòng ban",
                description: "Nhấn VÀO NÚT BA CHẤM ở hàng phòng ban bạn muốn thiết lập lộ trình thăng tiến.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-career-paths-2",
                targetId: ".guide-department-career-paths",
                title: "Bước-2: Chọn Lộ trình thăng tiến",
                description: "Nhấn vào 'Lộ trình thăng tiến' để xem và quản lý các nấc thang sự nghiệp của phòng ban.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-career-paths-3",
                targetId: "career-path-add-button",
                title: "Bước 3: Thêm bậc lộ trình",
                description: "Nhấn 'Thêm mới' để tạo bậc thăng tiến. Điền chức danh, cấp bậc hiện tại, bậc kế tiếp, điều kiện lên bậc như thời gian đảm nhiệm, KPI, năng lực, chứng chỉ hoặc đánh giá quản lý, sau đó lưu.",
                placement: "left",
                actionType: "click",
            },
        ],
    },
    {
        id: "hr-dossier-salary-range",
        title: "7. Khung lương chức danh",
        description: "Cấu hình dải lương, bậc lương và thành phần thu nhập theo chức danh của phòng ban.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "7. Khung lương",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        allowedRoutes: [/^\/admin\/departments\/[^/]+\/salary-range/],
        icon: <FolderOpenOutlined />,
        steps: [
            {
                id: "hr-dossier-salary-1",
                targetId: "department-more-button",
                title: "Bước 1: Mở menu tùy chọn phòng ban",
                description: "Nhấn VÀO NÚT BA CHẤM ở hàng phòng ban bạn muốn cấu hình khung lương.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-salary-2",
                targetId: ".guide-department-salary",
                title: "Bước 2: Chọn Khung lương",
                description: "Nhấn vào 'Khung lương' để vào trang quản lý cơ cấu thu nhập theo ngạch/bậc của phòng ban.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-salary-3",
                targetId: "dept-salary-range-content",
                title: "Bước 3: Thiết lập khung lương",
                description: "Bảng này hiển thị mức lương theo chức danh và bậc. Nhập lương tối thiểu, lương cơ bản, lương tối đa và các khoản thu nhập liên quan nếu có. Nên đối chiếu với lộ trình thăng tiến để mỗi bậc nghề nghiệp có khung lương tương ứng.",
                placement: "top",
            },
        ],
    },
    {
        id: "hr-dossier-performance",
        title: "8. Tiêu chí đánh giá theo bậc lương",
        description: "Định nghĩa tiêu chí, mức xếp loại và cách liên kết kết quả đánh giá với bậc lương, chức danh.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "8. Tiêu chí đánh giá",
        routePrefix: "/admin/departments",
        exactRoute: false,
        routePattern: /^\/admin\/departments/,
        icon: <AimOutlined />,
        steps: [
            {
                id: "hr-dossier-performance-1",
                targetId: "department-more-button",
                title: "Chuẩn bị tiêu chí đánh giá",
                description: "Tính năng này đang được hoàn thiện. Trong lúc chờ cập nhật, bạn nên chuẩn bị trước bộ tiêu chí theo từng chức danh và bậc lương: nhóm KPI, năng lực chuyên môn, năng lực hành vi, thang điểm, mức đạt và điều kiện xét nâng bậc.",
                placement: "left",
            },
        ],
    },
    {
        id: "hr-dossier-position-chart",
        title: "9. Bản đồ chức danh",
        description: "Nhìn tổng thể chức danh, quan hệ cấp bậc, số lượng nhân sự và trạng thái vị trí trong phòng ban.",
        module: "Bộ hồ sơ nhân sự",
        subModule: "9. Bản đồ chức danh",
        routePrefix: "/admin/departments",
        exactRoute: true,
        routePattern: /^\/admin\/departments$/,
        allowedRoutes: [/^\/admin\/departments\/[^/]+\/position-chart/],
        icon: <TeamOutlined />,
        steps: [
            {
                id: "hr-dossier-position-chart-1",
                targetId: "department-more-button",
                title: "Bước 1: Mở menu tùy chọn phòng ban",
                description: "Nhấn VÀO NÚT BA CHẤM ở hàng phòng ban bạn muốn xem bản đồ chức danh.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-position-chart-2",
                targetId: ".guide-department-position-chart",
                title: "Bước 2: Chọn Bản đồ chức danh",
                description: "Nhấn vào 'Bản đồ chức danh' để xem toàn bộ các chức danh, quan hệ cấp bậc và vị trí nhân sự hiện tại trong phòng ban.",
                placement: "left",
                actionType: "click",
            },
            {
                id: "hr-dossier-position-chart-3",
                targetId: "dept-position-chart-content",
                title: "Bước 3: Xem bản đồ chức danh",
                description: "Bảng này hiển thị chức danh, số nhân sự hiện tại, trạng thái vị trí và quan hệ cấp bậc. Dùng bản đồ này để kiểm tra chức danh nào chưa có JD, chưa có khung lương, chưa có lộ trình hoặc đang thiếu nhân sự so với cơ cấu.",
                placement: "top",
            },
        ],
    },
];
